version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: inventory_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
    container_name: inventory_backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/inventory
      - JWT_SECRET=your_jwt_secret

volumes:
  mongo_data:
